# Generated by Django 4.2 on 2023-04-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.BigIntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('warehouse_x', models.IntegerField()),
                ('warehouse_y', models.IntegerField()),
                ('destination_x', models.IntegerField()),
                ('destination_y', models.IntegerField()),
                ('ups_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('truck_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UDeliveryLocationD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.BigIntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'u_delivery_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UGoDeliverD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.IntegerField()),
                ('seq_num', models.BigIntegerField()),
            ],
            options={
                'db_table': 'u_go_deliver',
                'managed': False,
            },
        ),
    ]
