# Generated by Django 4.2 on 2023-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqNumD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.BigIntegerField()),
            ],
            options={
                'db_table': 'seqnum',
                'managed': False,
            },
        ),
    ]
